version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: cimg/android:2024.07.1-ndk
    environment:
      JVM_OPTS: -Xmx3500m
      GRADLE_OPTS: -Dorg.gradle.workers.max=1 -Dorg.gradle.daemon=false
    steps:
      - checkout
      - run: git submodule update --init --recursive
      - run: curl -OL https://go.dev/dl/go1.22.5.linux-amd64.tar.gz
      - run: tar -C "$HOME" -xzf go1.22.5.linux-amd64.tar.gz
      - run: echo 'export PATH="$HOME"/go/bin:"$PATH"' >> "$BASH_ENV"
      - restore_cache:
          key: jars-{{ checksum "build.gradle.kts" }}
      - restore_cache:
          key: go-{{ checksum "app/src/main/go/v2ray-plugin/go.sum" }}
      - run:
          name: Run Build
          command: ./gradlew assembleRelease --warning-mode all
      - save_cache:
          paths:
          - ~/go
          key: go-{{ checksum "app/src/main/go/v2ray-plugin/go.sum" }}
      - save_cache:
          paths:
            - ~/.gradle
            - ~/.android/build-cache
          key: jars-{{ checksum "build.gradle.kts" }}
      - store_artifacts:
          path: app/build/outputs/apk
          destination: apk
      - store_artifacts:
          path: app/build/reports
          destination: reports
